trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd $(System.DefaultWorkingDirectory)/apps/TodoListSPA
    npm install
    npm install -g @angular/cli
    ng build -c=production --output-path='$(Build.ArtifactStagingDirectory)/frontend'
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish frontend app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
    ArtifactName: 'frontend'

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime
    

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(System.DefaultWorkingDirectory)/apps/TodoListFn/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)/function --configuration Release'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish function app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/function'
    ArtifactName: 'function'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish templates'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/arm_templates'
    ArtifactName: 'templates'
