trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd $(System.DefaultWorkingDirectory)/apps/TodoListSPA
    npm install -g @angular/cli
    npm install
    ng build -c=production --output-path $(Build.ArtifactStagingDirectory)/frontend
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish frontend app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
    ArtifactName: 'frontend'

- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime
    
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(System.DefaultWorkingDirectory)/apps/TodoListFn/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(System.DefaultWorkingDirectory)/apps/TodoListFn/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)/function --configuration Release'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish function app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/function'
    ArtifactName: 'function'