trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd $(workingDirectory)/apps/TodoListSPA
    npm install -g @angular/cli
    npm install
    ng build -c=production
  displayName: 'npm install and build'

- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime
    
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(workingDirectory)/apps/TodoListFn/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(workingDirectory)/apps/TodoListFn/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'apps'
    publishLocation: 'Container'