trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules dist
    npm uninstall -g @angular/cli
    npm cache clean
    npm install -g @angular/cli
  displayName: 'npm install'

- script: |
    cd $(System.DefaultWorkingDirectory)/apps/TodoListSPA
    ng build -c=production --output-path='$(Build.ArtifactStagingDirectory)/frontend'
  displayName: 'ng build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish frontend app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
    ArtifactName: 'frontend'

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime
    
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(System.DefaultWorkingDirectory)/apps/TodoListFn/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(System.DefaultWorkingDirectory)/apps/TodoListFn/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)/function --configuration Release'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish function app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/function'
    ArtifactName: 'function'